- name: Disable password-based authentication on Raspberry Pi
  hosts: "*"
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: "password"

  tasks:
    - name: Update SSH configuration
      blockinfile:
        path: /etc/ssh/sshd_config
        block: |
          # Disable password-based authentication
          PasswordAuthentication no
      notify: Restart SSH service

  handlers:
    - name: Restart SSH service
      service:
        name: ssh
        state: restarted
