---
- name: install fail2ban and configure sshd
  hosts: "*"
  become: yes
  become_method: sudo
  vars:
    ansible_become_pass: "password"
  tasks:

  - name: install fail2ban
    apt:
      name:
        - fail2ban
      update_cache: yes

  - name: copy fail2ban configfiles
    copy:
      src: configfiles/debian-sshd-default.conf
      dest: /etc/fail2ban/jail.d/debian-sshd-default.conf
    ignore_errors: yes
    register: copy_result
  
  - name: Handle missing fail2ban config file
    fail:
      msg: |
        The fail2ban config file could not be found at the directory '{{ ansible_env.HOME }}/ansible/________/configfiles/'. Please provide the file manually.
    when: copy_result.failed

  - name: restart fail2ban
    systemd:
      state: restarted
      daemon_reload: yes
      name: fail2ban