http:
 #region routers 
  routers:
    portainer:
      entryPoints:
        - 'https'
      rule: 'Host(`portainer.beu-owen.duckdns.org`)'
      middlewares:
        - default-headers
        - https-redirectscheme
      tls: {}
      service: portainer

    pihole:
      entryPoints:
        - 'https'
      rule: 'Host(`pihole.beu-owen.duckdns.org`)'
      middlewares:
        - default-headers
        - addprefix-pihole
        - https-redirectscheme
      tls: {}
      service: pihole

#endregion
#region services
  services:
    portainer:
      loadBalancer:
        servers:
          - url: 'https://192.168.1.38:9443'
        passHostHeader: true

    pihole:
      loadBalancer:
        servers:
         - url: 'http://192.168.1.45:80'
        passHostHeader: true

#endregion
  middlewares:
    https-redirectscheme:
      redirectScheme:
        scheme: https
        permanent: true

    default-headers:
      headers:
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    idrac:
      headers:
        frameDeny: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https

    default-whitelist:
      ipWhiteList:
        sourceRange:
        - '10.0.0.0/8'
        - '192.168.0.0/16'
        - '192.168.1.0/16'
        - '192.168.5.0/16'
        - '172.16.0.0/12'

    secured:
      chain:
        middlewares:
        - default-whitelist
        - default-headers

    addprefix-pihole:
      addPrefix:
        prefix: '/admin'